#!/bin/bash
make
if [ $? -ne 0 ]; then
	echo "make returned with $?"
	exit 1
fi
sudo insmod reminder.ko
if [ $? -eq 1 ]; then
	echo "Module insertion failed"
	exit 1
fi
sudo chmod a+rwx /dev/reminder
if [ $? -eq 1 ]; then
	echo "Mode change of file /dev/reminder failed"
	exit 1
fi

if [ $# -eq 2 ]; then
	../userspace/main "$2"	
	if [ "$1" == "-s" ]; then
		sudo shutdown now
	elif [ "$1" == "-r" ]; then
		sudo reboot now
	else
		echo "Wrong input args"
		exit 0
	fi
else
	exit 0
fi
