#!/bin/bash
echo
echo "------------------"
echo "Compilation starts"
echo "------------------"
echo
gcc -std=gnu99 -Wall -o test main.c
if [ $? -ne 0 ]	then
	echo
	echo "-------!!------"
	echo "Compile failed!"
	echo "-------!!------"
	exit 1
fi
echo
echo "---------------------------------------------------"
echo "Compilation succedded, inserting module reminder.ko"
echo "---------------------------------------------------"
sudo insmod ../kernelspace/reminder.ko
if [ $? -ne 0 ] then
	echo
	echo "---------!!!---------"
	echo "Module insert failed!"
	echo "---------!!!---------"
	echo
	exit 1
fi
echo "------------------------------------------------------------------"
echo "Module was inserted with success, starting test with proper string"
echo "-------------------------------------------------------------------"
./main 
echo
echo "------------------------------"
echo "Removing module to show string"
echo "------------------------------"
echo
sudo rmmod
if [ $? -ne 0] then
	echo
	echo "----------!!!----------"
	echo "Removing module failed!"
	echo "----------!!!----------"
	echo	
	exit 1
fi
echo
echo "----------------------------------------------------------------------------"
echo "Above line should present test string, waiting 3 sec for second test"
echo "----------------------------------------------------------------------------"
echo
sleep 3
echo "----------------------------------"
echo "Inserting module reminder.ko again"
echo "----------------------------------"
echo
sudo insmod ../kernelspace/reminder.ko
if [ $? -ne 0 ] then
	echo
	echo "---------!!!---------"
	echo "Module insert failed!"
	echo "---------!!!---------"
	echo
	exit 1
fi

echo
echo "---------------------------------------------------------"
echo "Starting test with to long string, warnings should occure"
echo "---------------------------------------------------------"
echo
./main 1 
echo
echo "------------------------------"
echo "Removing module to show string"
echo "------------------------------"
echo
sudo rmmod
if [ $? -ne 0] then
	echo
	echo "----------!!!----------"
	echo "Removing module failed!"
	echo "----------!!!----------"
	echo	
	exit 1
fi
echo "END OF TEST END OF TEST END OF TEST END OF TEST END OF TEST END OF TEST END OF TEST"
	
