#!/bin/bash

clear
echo "------------------"
echo "Compilation starts"
echo "------------------"
echo
gcc -std=gnu99 -Wall -o main main.c
if [ $? -ne 0 ]; then
	echo
	echo "---------!!--------"
	echo "Compilation failed!"
	echo "---------!!--------"
	exit 1
fi
echo
echo "---------------------------------------------------"
echo "Compilation succedded, inserting module reminder.ko"
echo "---------------------------------------------------"
sudo insmod ../kernelspace/reminder.ko
if [ $? -ne 0 ]; then
	echo
	echo "-----------!!!----------"
	echo "Module insertion failed!"
	echo "-----------!!!----------"
	echo
	exit 1
fi
sudo chmod a+rwx /dev/reminder
echo "--------------------------------------------------------------------------"
echo "Module was inserted with success, starting test without string as argument"
echo "--------------------------------------------------------------------------"
./main 
echo
echo "------------------------------"
echo "Removing module to show string"
echo "------------------------------"
echo
sudo rmmod reminder
if [ $? -ne 0 ]; then
	echo
	echo "----------!!!----------"
	echo "Module removing failed!"
	echo "----------!!!----------"
	echo	
	exit 1
fi
echo
echo "------------------------------------------------------------------------"
echo "Above line should present test string. Now waiting 3 sec for second test"
echo "------------------------------------------------------------------------"
echo
sleep 3
echo "----------------------------------"
echo "Inserting module reminder.ko again"
echo "----------------------------------"
echo
sudo insmod ../kernelspace/reminder.ko
if [ $? -ne 0 ]; then
	echo
	echo "-----------!!!----------"
	echo "Module insertion failed!"
	echo "-----------!!!----------"
	echo
	exit 1
fi
sudo chmod a+rwx /dev/reminder
echo
echo "-------------------------------------------"
echo "Starting test with string as input argument"
echo "-------------------------------------------"
echo
./main "raz dwa"
echo
echo "------------------------------"
echo "Removing module to show string"
echo "------------------------------"
echo
sudo rmmod reminder
if [ $? -ne 0 ]; then
	echo
	echo "----------!!!----------"
	echo "Removing module failed!"
	echo "----------!!!----------"
	echo	
	exit 1
fi

echo "If you don't see \"module work\", check whether messages are in dmesg"

echo "END OF TEST END OF TEST END OF TEST END OF TEST END OF TEST END OF TEST END OF TEST"
	
